#!/bin/bash
version=$(wget http://www.playonlinux.com/script_files/version.php -O-)
mkdir -p $version
wget http://www.playonlinux.com/script_files/PlayOnLinux/$version/PlayOnLinux_$version.deb -O $version/PlayOnLinux_$version.deb
cd $version
fakeroot alien --to-rpm -g -c PlayOnLinux_$version.deb
cd playonlinux-$version
cat << EOF > playonlinux.spec
Name: playonlinux
Version: $version
Summary: PlayOnLinux is a front-end for wine. It permits you to install Windows Games and softwares on Linux.
License: see /usr/share/doc/playonlinux/copyright
BuildArch:noarch
Release: fedora0
Distribution: Fedora
Group: PlayOnLinux
URL:http://www.playonlinux.com/
VenDor:PlayOnLinux
Packager:MulX <os2mule@gmail.com>
Buildroot: $(dirname $PWD)/playonlinux-$version
Requires:unzip, wine, wget, xterm, python > 2.4 ,wxPython, bash, ImageMagick, cabextract,  gettext

%define _rpmdir ../
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0
%description
PlayOnLinux is able to install Windows
games on your Linux Distro.

%files
%defattr(-,root,root)
%dir "/"
%dir "/usr/"
/usr/*
EOF
rpmbuild -bb playonlinux.spec
cd ..
rpm --addsign *.rpm
