#!/bin/bash

VERSION=$1
if [ "$VERSION" = "" ]
then
	echo "You must specify a version"
	exit
fi
DIRNAME="base"
DIRECTORY="$HOME/git/$DIRNAME"
GITDIRECTORY="$HOME/git/PlayOnLinux.git" #utilisé pour le dossier git current
export FINAL="$HOME/www/PlayOnLinux"
if [ "$VERSION" = "" ]
then
	echo "You need to specify a version"
	exit	
fi
echo "Welcome to PlayOnLinux builder script"
echo "Building $VERSION from GIT"
# Generate control file
echo "Generating control file"
cd "$DIRECTORY/DEBIAN"
cat << EOF > /dev/null # VOir en bas !
Package: playonlinux
Conflicts: playonlinux-beta
Version: $VERSION$REVISION
Section: misc
Priority: optional
Architecture: all
Depends: unzip, wine | wine-stable | wine-unstable, wget, xterm, python, python-wxgtk2.8, imagemagick, cabextract, icoutils, p7zip-full
Maintainer: PlayOnLinux Packaging <packages@playonlinux.com> 
Description: This program is a front-end for wine. 
 It permits you to install Windows Games and softwares 
 on Linux. It allows you to manage differents virtual hard drive, 
 and several wine versions.
 Copyright 2011 PlayOnLinux team <contact@playonlinux.com>
EOF

#mise à jour du git
mkdir -p "$GITDIRECTORY"
cd "$GITDIRECTORY"
if [ ! -d .git ]
then
	echo "This isn't a git directory, initializing..."
	#dossier pour identifier un git
	mkdir .git
	#fichier qui contient le strict minimum pour git init
	cat << EOF > .git/config
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = git@github.com:PlayOnLinux/POL-POM-4.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
EOF
	#on laisse git finir l'init
	git init
fi
#télécharge les maj depuis le dernier git pull
#rmq: is aucun télécharge tout est dl depuis le début
git pull

# Making .tar.gz
echo "Making PlayOnLinux_$VERSION.tar.gz generic package"
fakeroot git archive --format=tar --prefix=playonlinux/ $VERSION | gzip> $DIRECTORY/usr/share/PlayOnLinux_$VERSION.tar.gz || exit 1
cd "$DIRECTORY/usr/share"

#supprime l'ancien dossier playonlinux -- au cas où
rm -rf $DIRECTORY/usr/share/playonlinux
#extraction pour dpkg-deb
tar xf PlayOnLinux_$VERSION.tar.gz

# Moving .tar.gz
echo "Moving PlayOnLinux_$VERSION.tar.gz"
mkdir -p $FINAL/$VERSION
mv PlayOnLinux_$VERSION.tar.gz "$FINAL/$VERSION"

# Making changelog
echo "Updating changelog"
cp "$DIRECTORY/usr/share/playonlinux/CHANGELOG" "$DIRECTORY/usr/share/doc/playonlinux/changelog"
gzip -9 "$DIRECTORY/usr/share/doc/playonlinux/changelog"
rm "$DIRECTORY/usr/share/playonlinux/LICENCE"
rm "$DIRECTORY/usr/share/playonlinux/.gitignore"

echo "Building PlayOnLinux_$VERSION.deb"
cd "$DIRECTORY"
cd ..
installed_size="$(du "$DIRECTORY/usr" | tail -n 1 | awk '{print $1}')"

cd "$DIRECTORY/DEBIAN"
cat << EOF > control
Package: playonlinux
Conflicts: playonlinux-beta
Version: $VERSION$REVISION
Section: misc
Priority: optional
Installed-Size: $installed_size
Architecture: all
Depends: unzip, wine | wine-stable | wine-unstable, wget, xterm, python, python-wxgtk2.8, imagemagick, cabextract, icoutils
Maintainer: PlayOnLinux Packaging <packages@playonlinux.com>
Description: This program is a front-end for wine.
 It permits you to install Windows Games and softwares
 on Linux. It allows you to manage differents virtual hard drive,
 and several wine versions.
 Copyright 2011 PlayOnLinux team <contact@playonlinux.com>
EOF

cd "$DIRECTORY"
cd ..

fakeroot dpkg-deb --build $DIRNAME

# Moving .deb
echo "Moving deb"
mv $DIRNAME.deb "$FINAL/$VERSION/PlayOnLinux_$VERSION.deb"

# Cleaning
echo "Cleaning"
rm "$DIRECTORY/DEBIAN/control"
rm -rf "$DIRECTORY/usr/share/playonlinux"
rm "$DIRECTORY/usr/share/doc/playonlinux/changelog.gz"

# Making rpm
echo "Building rpm"
cd $HOME/PlayOnLinux_Tools/PlayOnLinux_Packager
./generate_rpm "$VERSION"
# Updating website 
# echo "$VERSION" > "$HOME/www/script_files/version.php"

echo ""
echo "PlayOnLinux $VERSION is now available ! Don't forget to run make_repository"
