#!/bin/bash
#version=$(wget http://www.playonlinux.com/script_files/version.php -O-)
version="$1"
[ "$1" = "" ] && echo "Quelle version ?" && exit 1

cd $FINAL/$version/
fakeroot alien --to-rpm -g -c PlayOnLinux_$version.deb
cd playonlinux-$version
cat << EOF > playonlinux.spec
Name: playonlinux
Version: $version
Summary: PlayOnLinux is a front-end for wine. It permits you to install Windows Games and softwares on Linux.
License: see /usr/share/doc/playonlinux/copyright
BuildArch:noarch
Release: fedora0
Distribution: Fedora
Group: PlayOnLinux
URL:http://www.playonlinux.com/
VenDor:PlayOnLinux
Packager:PlayOnLinux Packaging <packages@playonlinux.com>
Buildroot: /home/tinou/www/PlayOnLinux/$version/playonlinux-$version
Requires:unzip, wine, wget, xterm, python > 2.4 ,wxPython, bash, ImageMagick, cabextract,  gettext, redhat-lsb, p7zip, p7zip-plugins, icoutils

%define _rpmdir ../
%define _rpmfilename PlayOnLinux_%%{VERSION}_%%{RELEASE}.rpm
%define _unpackaged_files_terminate_build 0
%global _binaries_in_noarch_packages_terminate_build 0

%description
PlayOnLinux is able to install Windows
games on your Linux Distro.

%files
%defattr(-,root,root)
%dir "/"
%dir "/usr/"
/usr/*
EOF
## FIXME 
mkdir -p /home/tinou/rpmbuild/BUILDROOT/playonlinux-$version-fedora0.x86_64
cp -r usr /home/tinou/rpmbuild/BUILDROOT/playonlinux-$version-fedora0.x86_64
rpmbuild  -bb playonlinux.spec --nodeps 


echo "Fini rpmbuild"
cd $FINAL/$version/
rpm --addsign *.rpm

rm -r playonlinux-$version
rm playonlinux.spec
