#!/bin/bash

DIRNAME="base"
DIRECTORY="$HOME/git/$DIRNAME"
GITDIRECTORY="$HOME/git/PlayOnLinux.git" #utilisé pour le dossier git current
cd "$GITDIRECTORY"
git pull

export FINAL="$HOME/PlayOnLinux-beta/files"
mkdir -p "$FINAL" 
cd "$GITDIRECTORY/python/lib"
VERSION="$(cat Variables.py | grep "VERSION" | grep "] = " | cut -d \" -f4)"
export VERSION="${VERSION/-dev/}"
echo "Version detected: $VERSION"
mkdir -p "$HOME/.polpackager/increments"
cur_file="$HOME/.polpackager/increments/$VERSION"
touch "$cur_file"

ver=$(cat "$cur_file")
ver=$((ver+1))
[ "$ver" = "0" ] && ver=$((ver+1))
echo -n $ver > "$cur_file"
export ver
echo "Increment : $ver"

echo "Welcome to PlayOnLinux builder script"
echo "Building $VERSION from GIT"
# Generate control file
echo "Generating control file"
cd "$DIRECTORY/DEBIAN"
cat << EOF > /dev/null # VOir en bas !
Package: playonlinux-beta
Conflicts: playonlinux
Version: $VERSION-$ver
Section: misc
Priority: optional
Architecture: all
Depends: unzip, wine | wine-stable | wine-unstable, wget, xterm, python, python-wxgtk2.8, imagemagick, cabextract, icoutils
Maintainer: PlayOnLinux Packaging <packages@playonlinux.com> 
Description: This program is a front-end for wine. 
 It permits you to install Windows Games and softwares 
 on Linux. It allows you to manage differents virtual hard drive, 
 and several wine versions.
 Copyright 2011 PlayOnLinux team <contact@playonlinux.com>
EOF

#mise à jour du git
mkdir -p "$GITDIRECTORY"
cd "$GITDIRECTORY"
if [ ! -d .git ]
then
	echo "This isn't a git directory, initializing..."
	#dossier pour identifier un git
	mkdir .git
	#fichier qui contient le strict minimum pour git init
	cat << EOF > .git/config
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = git@github.com:PlayOnLinux/POL-POM-4.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
EOF
	#on laisse git finir l'init
	git init
fi
#télécharge les maj depuis le dernier git pull
#rmq: is aucun télécharge tout est dl depuis le début
git pull

# Making .tar.gz
echo "Making PlayOnLinux_$VERSION-$ver.tar.gz generic package"
fakeroot git archive --format=tar --prefix=playonlinux/ HEAD | gzip> $DIRECTORY/usr/share/PlayOnLinux-beta_$VERSION-$ver.tar.gz || exit 1
cd "$DIRECTORY/usr/share"

#supprime l'ancien dossier playonlinux -- au cas où
rm -rf $DIRECTORY/usr/share/playonlinux
#extraction pour dpkg-deb
tar xf PlayOnLinux-beta_$VERSION-$ver.tar.gz

# Moving .tar.gz
echo "Moving PlayOnLinux_$VERSION-$ver.tar.gz"
mkdir -p $FINAL/$VERSION-$ver
mv PlayOnLinux-beta_$VERSION-$ver.tar.gz "$FINAL/$VERSION-$ver"

# Making changelog
echo "Updating changelog"
cp "$DIRECTORY/usr/share/playonlinux/CHANGELOG" "$DIRECTORY/usr/share/doc/playonlinux/changelog"
gzip -9 "$DIRECTORY/usr/share/doc/playonlinux/changelog"
rm "$DIRECTORY/usr/share/playonlinux/LICENCE"
rm "$DIRECTORY/usr/share/playonlinux/.gitignore"

echo "Building PlayOnLinux_$VERSION-$ver.deb"
cd "$DIRECTORY"
cd ..
installed_size="$(du "$DIRECTORY/usr" | tail -n 1 | awk '{print $1}')"

cd "$DIRECTORY/DEBIAN"
cat << EOF > control
Package: playonlinux-beta
Conflicts: playonlinux
Version: $VERSION-$ver
Section: misc
Priority: optional
Installed-Size: $installed_size
Architecture: all
Depends: unzip, wine | wine-stable | wine-unstable, wget, xterm, python, python-wxgtk2.8, imagemagick, cabextract, icoutils
Maintainer: PlayOnLinux Packaging <packages@playonlinux.com>
Description: This program is a front-end for wine.
 It permits you to install Windows Games and softwares
 on Linux. It allows you to manage differents virtual hard drive,
 and several wine versions.
 Copyright 2011 PlayOnLinux team <contact@playonlinux.com>
EOF

cd "$DIRECTORY"
cd ..

fakeroot dpkg-deb --build $DIRNAME

# Moving .deb
echo "Moving deb"
mv $DIRNAME.deb "$FINAL/$VERSION-$ver/PlayOnLinux-beta_$VERSION-$ver.deb"

# Cleaning
echo "Cleaning"
rm "$DIRECTORY/DEBIAN/control"
rm -rf "$DIRECTORY/usr/share/playonlinux"
rm "$DIRECTORY/usr/share/doc/playonlinux/changelog.gz"

cd "$HOME/PlayOnLinux_Tools/PlayOnLinux_Packager"
bash make_repository_beta
